package main

import "time"

type TokenData struct {
	ID              string `json:"id"`
	Symbol          string `json:"symbol"`
	Name            string `json:"name"`
	AssetPlatformID string `json:"asset_platform_id"`
	Platforms       struct {
		Ethereum string `json:"ethereum"`
	} `json:"platforms"`
	CountryOrigin                string  `json:"country_origin"`
	GenesisDate                  string  `json:"genesis_date"`
	ContractAddress              string  `json:"contract_address"`
	SentimentVotesUpPercentage   float64 `json:"sentiment_votes_up_percentage"`
	SentimentVotesDownPercentage float64 `json:"sentiment_votes_down_percentage"`
	IcoData                      struct {
		IcoStartDate time.Time   `json:"ico_start_date"`
		IcoEndDate   time.Time   `json:"ico_end_date"`
		ShortDesc    string      `json:"short_desc"`
		Description  interface{} `json:"description"`
		Links        struct {
		} `json:"links"`
		SoftcapCurrency         string      `json:"softcap_currency"`
		HardcapCurrency         string      `json:"hardcap_currency"`
		TotalRaisedCurrency     string      `json:"total_raised_currency"`
		SoftcapAmount           string      `json:"softcap_amount"`
		HardcapAmount           string      `json:"hardcap_amount"`
		TotalRaised             string      `json:"total_raised"`
		QuotePreSaleCurrency    string      `json:"quote_pre_sale_currency"`
		BasePreSaleAmount       string      `json:"base_pre_sale_amount"`
		QuotePreSaleAmount      string      `json:"quote_pre_sale_amount"`
		QuotePublicSaleCurrency string      `json:"quote_public_sale_currency"`
		BasePublicSaleAmount    float64     `json:"base_public_sale_amount"`
		QuotePublicSaleAmount   float64     `json:"quote_public_sale_amount"`
		AcceptingCurrencies     string      `json:"accepting_currencies"`
		CountryOrigin           string      `json:"country_origin"`
		PreSaleStartDate        time.Time   `json:"pre_sale_start_date"`
		PreSaleEndDate          time.Time   `json:"pre_sale_end_date"`
		WhitelistURL            string      `json:"whitelist_url"`
		WhitelistStartDate      interface{} `json:"whitelist_start_date"`
		WhitelistEndDate        interface{} `json:"whitelist_end_date"`
		BountyDetailURL         string      `json:"bounty_detail_url"`
		AmountForSale           string      `json:"amount_for_sale"`
		KycRequired             bool        `json:"kyc_required"`
		WhitelistAvailable      interface{} `json:"whitelist_available"`
		PreSaleAvailable        bool        `json:"pre_sale_available"`
		PreSaleEnded            bool        `json:"pre_sale_ended"`
	} `json:"ico_data"`
	MarketCapRank       int     `json:"market_cap_rank"`
	CoingeckoRank       int     `json:"coingecko_rank"`
	CoingeckoScore      float64 `json:"coingecko_score"`
	DeveloperScore      float64 `json:"developer_score"`
	CommunityScore      float64 `json:"community_score"`
	LiquidityScore      float64 `json:"liquidity_score"`
	PublicInterestScore float64 `json:"public_interest_score"`
	MarketData          struct {
		CurrentPrice struct {
			Aed  float64 `json:"aed"`
			Ars  int     `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  int     `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  int     `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  int     `json:"huf"`
			Idr  int     `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  int     `json:"jpy"`
			Krw  int     `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  int     `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  int     `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  int     `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  int     `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  int     `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats int     `json:"sats"`
		} `json:"current_price"`
		TotalValueLocked interface{} `json:"total_value_locked"`
		McapToTvlRatio   interface{} `json:"mcap_to_tvl_ratio"`
		FdvToTvlRatio    interface{} `json:"fdv_to_tvl_ratio"`
		Roi              struct {
			Times      float64 `json:"times"`
			Currency   string  `json:"currency"`
			Percentage float64 `json:"percentage"`
		} `json:"roi"`
		Ath struct {
			Aed  float64 `json:"aed"`
			Ars  int     `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  int     `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  int     `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  int     `json:"huf"`
			Idr  int     `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  int     `json:"inr"`
			Jpy  int     `json:"jpy"`
			Krw  int     `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  int     `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  int     `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  int     `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  int     `json:"php"`
			Pkr  int     `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  int     `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  int     `json:"vef"`
			Vnd  int     `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  int     `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats int     `json:"sats"`
		} `json:"ath"`
		AthChangePercentage struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats float64 `json:"sats"`
		} `json:"ath_change_percentage"`
		AthDate struct {
			Aed  time.Time `json:"aed"`
			Ars  time.Time `json:"ars"`
			Aud  time.Time `json:"aud"`
			Bch  time.Time `json:"bch"`
			Bdt  time.Time `json:"bdt"`
			Bhd  time.Time `json:"bhd"`
			Bmd  time.Time `json:"bmd"`
			Bnb  time.Time `json:"bnb"`
			Brl  time.Time `json:"brl"`
			Btc  time.Time `json:"btc"`
			Cad  time.Time `json:"cad"`
			Chf  time.Time `json:"chf"`
			Clp  time.Time `json:"clp"`
			Cny  time.Time `json:"cny"`
			Czk  time.Time `json:"czk"`
			Dkk  time.Time `json:"dkk"`
			Dot  time.Time `json:"dot"`
			Eos  time.Time `json:"eos"`
			Eth  time.Time `json:"eth"`
			Eur  time.Time `json:"eur"`
			Gbp  time.Time `json:"gbp"`
			Hkd  time.Time `json:"hkd"`
			Huf  time.Time `json:"huf"`
			Idr  time.Time `json:"idr"`
			Ils  time.Time `json:"ils"`
			Inr  time.Time `json:"inr"`
			Jpy  time.Time `json:"jpy"`
			Krw  time.Time `json:"krw"`
			Kwd  time.Time `json:"kwd"`
			Lkr  time.Time `json:"lkr"`
			Ltc  time.Time `json:"ltc"`
			Mmk  time.Time `json:"mmk"`
			Mxn  time.Time `json:"mxn"`
			Myr  time.Time `json:"myr"`
			Ngn  time.Time `json:"ngn"`
			Nok  time.Time `json:"nok"`
			Nzd  time.Time `json:"nzd"`
			Php  time.Time `json:"php"`
			Pkr  time.Time `json:"pkr"`
			Pln  time.Time `json:"pln"`
			Rub  time.Time `json:"rub"`
			Sar  time.Time `json:"sar"`
			Sek  time.Time `json:"sek"`
			Sgd  time.Time `json:"sgd"`
			Thb  time.Time `json:"thb"`
			Try  time.Time `json:"try"`
			Twd  time.Time `json:"twd"`
			Uah  time.Time `json:"uah"`
			Usd  time.Time `json:"usd"`
			Vef  time.Time `json:"vef"`
			Vnd  time.Time `json:"vnd"`
			Xag  time.Time `json:"xag"`
			Xau  time.Time `json:"xau"`
			Xdr  time.Time `json:"xdr"`
			Xlm  time.Time `json:"xlm"`
			Xrp  time.Time `json:"xrp"`
			Yfi  time.Time `json:"yfi"`
			Zar  time.Time `json:"zar"`
			Bits time.Time `json:"bits"`
			Link time.Time `json:"link"`
			Sats time.Time `json:"sats"`
		} `json:"ath_date"`
		Atl struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats int     `json:"sats"`
		} `json:"atl"`
		AtlChangePercentage struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats float64 `json:"sats"`
		} `json:"atl_change_percentage"`
		AtlDate struct {
			Aed  time.Time `json:"aed"`
			Ars  time.Time `json:"ars"`
			Aud  time.Time `json:"aud"`
			Bch  time.Time `json:"bch"`
			Bdt  time.Time `json:"bdt"`
			Bhd  time.Time `json:"bhd"`
			Bmd  time.Time `json:"bmd"`
			Bnb  time.Time `json:"bnb"`
			Brl  time.Time `json:"brl"`
			Btc  time.Time `json:"btc"`
			Cad  time.Time `json:"cad"`
			Chf  time.Time `json:"chf"`
			Clp  time.Time `json:"clp"`
			Cny  time.Time `json:"cny"`
			Czk  time.Time `json:"czk"`
			Dkk  time.Time `json:"dkk"`
			Dot  time.Time `json:"dot"`
			Eos  time.Time `json:"eos"`
			Eth  time.Time `json:"eth"`
			Eur  time.Time `json:"eur"`
			Gbp  time.Time `json:"gbp"`
			Hkd  time.Time `json:"hkd"`
			Huf  time.Time `json:"huf"`
			Idr  time.Time `json:"idr"`
			Ils  time.Time `json:"ils"`
			Inr  time.Time `json:"inr"`
			Jpy  time.Time `json:"jpy"`
			Krw  time.Time `json:"krw"`
			Kwd  time.Time `json:"kwd"`
			Lkr  time.Time `json:"lkr"`
			Ltc  time.Time `json:"ltc"`
			Mmk  time.Time `json:"mmk"`
			Mxn  time.Time `json:"mxn"`
			Myr  time.Time `json:"myr"`
			Ngn  time.Time `json:"ngn"`
			Nok  time.Time `json:"nok"`
			Nzd  time.Time `json:"nzd"`
			Php  time.Time `json:"php"`
			Pkr  time.Time `json:"pkr"`
			Pln  time.Time `json:"pln"`
			Rub  time.Time `json:"rub"`
			Sar  time.Time `json:"sar"`
			Sek  time.Time `json:"sek"`
			Sgd  time.Time `json:"sgd"`
			Thb  time.Time `json:"thb"`
			Try  time.Time `json:"try"`
			Twd  time.Time `json:"twd"`
			Uah  time.Time `json:"uah"`
			Usd  time.Time `json:"usd"`
			Vef  time.Time `json:"vef"`
			Vnd  time.Time `json:"vnd"`
			Xag  time.Time `json:"xag"`
			Xau  time.Time `json:"xau"`
			Xdr  time.Time `json:"xdr"`
			Xlm  time.Time `json:"xlm"`
			Xrp  time.Time `json:"xrp"`
			Yfi  time.Time `json:"yfi"`
			Zar  time.Time `json:"zar"`
			Bits time.Time `json:"bits"`
			Link time.Time `json:"link"`
			Sats time.Time `json:"sats"`
		} `json:"atl_date"`
		MarketCap struct {
			Aed  int64 `json:"aed"`
			Ars  int64 `json:"ars"`
			Aud  int64 `json:"aud"`
			Bch  int   `json:"bch"`
			Bdt  int64 `json:"bdt"`
			Bhd  int   `json:"bhd"`
			Bmd  int64 `json:"bmd"`
			Bnb  int   `json:"bnb"`
			Brl  int64 `json:"brl"`
			Btc  int   `json:"btc"`
			Cad  int64 `json:"cad"`
			Chf  int64 `json:"chf"`
			Clp  int64 `json:"clp"`
			Cny  int64 `json:"cny"`
			Czk  int64 `json:"czk"`
			Dkk  int64 `json:"dkk"`
			Dot  int   `json:"dot"`
			Eos  int   `json:"eos"`
			Eth  int   `json:"eth"`
			Eur  int64 `json:"eur"`
			Gbp  int64 `json:"gbp"`
			Hkd  int64 `json:"hkd"`
			Huf  int64 `json:"huf"`
			Idr  int64 `json:"idr"`
			Ils  int64 `json:"ils"`
			Inr  int64 `json:"inr"`
			Jpy  int64 `json:"jpy"`
			Krw  int64 `json:"krw"`
			Kwd  int   `json:"kwd"`
			Lkr  int64 `json:"lkr"`
			Ltc  int   `json:"ltc"`
			Mmk  int64 `json:"mmk"`
			Mxn  int64 `json:"mxn"`
			Myr  int64 `json:"myr"`
			Ngn  int64 `json:"ngn"`
			Nok  int64 `json:"nok"`
			Nzd  int64 `json:"nzd"`
			Php  int64 `json:"php"`
			Pkr  int64 `json:"pkr"`
			Pln  int64 `json:"pln"`
			Rub  int64 `json:"rub"`
			Sar  int64 `json:"sar"`
			Sek  int64 `json:"sek"`
			Sgd  int64 `json:"sgd"`
			Thb  int64 `json:"thb"`
			Try  int64 `json:"try"`
			Twd  int64 `json:"twd"`
			Uah  int64 `json:"uah"`
			Usd  int64 `json:"usd"`
			Vef  int   `json:"vef"`
			Vnd  int64 `json:"vnd"`
			Xag  int   `json:"xag"`
			Xau  int   `json:"xau"`
			Xdr  int64 `json:"xdr"`
			Xlm  int64 `json:"xlm"`
			Xrp  int64 `json:"xrp"`
			Yfi  int   `json:"yfi"`
			Zar  int64 `json:"zar"`
			Bits int64 `json:"bits"`
			Link int   `json:"link"`
			Sats int64 `json:"sats"`
		} `json:"market_cap"`
		MarketCapRank         int `json:"market_cap_rank"`
		FullyDilutedValuation struct {
			Aed  int64 `json:"aed"`
			Ars  int64 `json:"ars"`
			Aud  int64 `json:"aud"`
			Bch  int   `json:"bch"`
			Bdt  int64 `json:"bdt"`
			Bhd  int   `json:"bhd"`
			Bmd  int64 `json:"bmd"`
			Bnb  int   `json:"bnb"`
			Brl  int64 `json:"brl"`
			Btc  int   `json:"btc"`
			Cad  int64 `json:"cad"`
			Chf  int64 `json:"chf"`
			Clp  int64 `json:"clp"`
			Cny  int64 `json:"cny"`
			Czk  int64 `json:"czk"`
			Dkk  int64 `json:"dkk"`
			Dot  int   `json:"dot"`
			Eos  int   `json:"eos"`
			Eth  int   `json:"eth"`
			Eur  int64 `json:"eur"`
			Gbp  int64 `json:"gbp"`
			Hkd  int64 `json:"hkd"`
			Huf  int64 `json:"huf"`
			Idr  int64 `json:"idr"`
			Ils  int64 `json:"ils"`
			Inr  int64 `json:"inr"`
			Jpy  int64 `json:"jpy"`
			Krw  int64 `json:"krw"`
			Kwd  int   `json:"kwd"`
			Lkr  int64 `json:"lkr"`
			Ltc  int   `json:"ltc"`
			Mmk  int64 `json:"mmk"`
			Mxn  int64 `json:"mxn"`
			Myr  int64 `json:"myr"`
			Ngn  int64 `json:"ngn"`
			Nok  int64 `json:"nok"`
			Nzd  int64 `json:"nzd"`
			Php  int64 `json:"php"`
			Pkr  int64 `json:"pkr"`
			Pln  int64 `json:"pln"`
			Rub  int64 `json:"rub"`
			Sar  int64 `json:"sar"`
			Sek  int64 `json:"sek"`
			Sgd  int64 `json:"sgd"`
			Thb  int64 `json:"thb"`
			Try  int64 `json:"try"`
			Twd  int64 `json:"twd"`
			Uah  int64 `json:"uah"`
			Usd  int64 `json:"usd"`
			Vef  int   `json:"vef"`
			Vnd  int64 `json:"vnd"`
			Xag  int   `json:"xag"`
			Xau  int   `json:"xau"`
			Xdr  int64 `json:"xdr"`
			Xlm  int64 `json:"xlm"`
			Xrp  int64 `json:"xrp"`
			Yfi  int   `json:"yfi"`
			Zar  int64 `json:"zar"`
			Bits int64 `json:"bits"`
			Link int   `json:"link"`
			Sats int64 `json:"sats"`
		} `json:"fully_diluted_valuation"`
		TotalVolume struct {
			Aed  int     `json:"aed"`
			Ars  int64   `json:"ars"`
			Aud  int     `json:"aud"`
			Bch  int     `json:"bch"`
			Bdt  int64   `json:"bdt"`
			Bhd  int     `json:"bhd"`
			Bmd  int     `json:"bmd"`
			Bnb  int     `json:"bnb"`
			Brl  int     `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  int     `json:"cad"`
			Chf  int     `json:"chf"`
			Clp  int64   `json:"clp"`
			Cny  int     `json:"cny"`
			Czk  int     `json:"czk"`
			Dkk  int     `json:"dkk"`
			Dot  int     `json:"dot"`
			Eos  int     `json:"eos"`
			Eth  int     `json:"eth"`
			Eur  int     `json:"eur"`
			Gbp  int     `json:"gbp"`
			Hkd  int     `json:"hkd"`
			Huf  int64   `json:"huf"`
			Idr  int64   `json:"idr"`
			Ils  int     `json:"ils"`
			Inr  int64   `json:"inr"`
			Jpy  int64   `json:"jpy"`
			Krw  int64   `json:"krw"`
			Kwd  int     `json:"kwd"`
			Lkr  int64   `json:"lkr"`
			Ltc  int     `json:"ltc"`
			Mmk  int64   `json:"mmk"`
			Mxn  int     `json:"mxn"`
			Myr  int     `json:"myr"`
			Ngn  int64   `json:"ngn"`
			Nok  int     `json:"nok"`
			Nzd  int     `json:"nzd"`
			Php  int64   `json:"php"`
			Pkr  int64   `json:"pkr"`
			Pln  int     `json:"pln"`
			Rub  int64   `json:"rub"`
			Sar  int     `json:"sar"`
			Sek  int     `json:"sek"`
			Sgd  int     `json:"sgd"`
			Thb  int     `json:"thb"`
			Try  int     `json:"try"`
			Twd  int     `json:"twd"`
			Uah  int     `json:"uah"`
			Usd  int     `json:"usd"`
			Vef  int     `json:"vef"`
			Vnd  int64   `json:"vnd"`
			Xag  int     `json:"xag"`
			Xau  int     `json:"xau"`
			Xdr  int     `json:"xdr"`
			Xlm  int     `json:"xlm"`
			Xrp  int     `json:"xrp"`
			Yfi  int     `json:"yfi"`
			Zar  int     `json:"zar"`
			Bits int     `json:"bits"`
			Link int     `json:"link"`
			Sats int64   `json:"sats"`
		} `json:"total_volume"`
		High24H struct {
			Aed  float64 `json:"aed"`
			Ars  int     `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  int     `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  int     `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  int     `json:"huf"`
			Idr  int     `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  int     `json:"jpy"`
			Krw  int     `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  int     `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  int     `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  int     `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  int     `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  int     `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats int     `json:"sats"`
		} `json:"high_24h"`
		Low24H struct {
			Aed  float64 `json:"aed"`
			Ars  int     `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  int     `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  int     `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  int     `json:"huf"`
			Idr  int     `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  int     `json:"jpy"`
			Krw  int     `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  int     `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  int     `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  int     `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  int     `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  int     `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats int     `json:"sats"`
		} `json:"low_24h"`
		PriceChange24H               float64 `json:"price_change_24h"`
		PriceChangePercentage24H     float64 `json:"price_change_percentage_24h"`
		PriceChangePercentage7D      float64 `json:"price_change_percentage_7d"`
		PriceChangePercentage14D     float64 `json:"price_change_percentage_14d"`
		PriceChangePercentage30D     float64 `json:"price_change_percentage_30d"`
		PriceChangePercentage60D     float64 `json:"price_change_percentage_60d"`
		PriceChangePercentage200D    float64 `json:"price_change_percentage_200d"`
		PriceChangePercentage1Y      float64 `json:"price_change_percentage_1y"`
		MarketCapChange24H           float64 `json:"market_cap_change_24h"`
		MarketCapChangePercentage24H float64 `json:"market_cap_change_percentage_24h"`
		PriceChange24HInCurrency     struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats float64 `json:"sats"`
		} `json:"price_change_24h_in_currency"`
		PriceChangePercentage1HInCurrency struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats float64 `json:"sats"`
		} `json:"price_change_percentage_1h_in_currency"`
		PriceChangePercentage24HInCurrency struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats float64 `json:"sats"`
		} `json:"price_change_percentage_24h_in_currency"`
		PriceChangePercentage7DInCurrency struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats float64 `json:"sats"`
		} `json:"price_change_percentage_7d_in_currency"`
		PriceChangePercentage14DInCurrency struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats float64 `json:"sats"`
		} `json:"price_change_percentage_14d_in_currency"`
		PriceChangePercentage30DInCurrency struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats float64 `json:"sats"`
		} `json:"price_change_percentage_30d_in_currency"`
		PriceChangePercentage60DInCurrency struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats float64 `json:"sats"`
		} `json:"price_change_percentage_60d_in_currency"`
		PriceChangePercentage200DInCurrency struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats float64 `json:"sats"`
		} `json:"price_change_percentage_200d_in_currency"`
		PriceChangePercentage1YInCurrency struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats float64 `json:"sats"`
		} `json:"price_change_percentage_1y_in_currency"`
		MarketCapChange24HInCurrency struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats float64 `json:"sats"`
		} `json:"market_cap_change_24h_in_currency"`
		MarketCapChangePercentage24HInCurrency struct {
			Aed  float64 `json:"aed"`
			Ars  float64 `json:"ars"`
			Aud  float64 `json:"aud"`
			Bch  float64 `json:"bch"`
			Bdt  float64 `json:"bdt"`
			Bhd  float64 `json:"bhd"`
			Bmd  float64 `json:"bmd"`
			Bnb  float64 `json:"bnb"`
			Brl  float64 `json:"brl"`
			Btc  float64 `json:"btc"`
			Cad  float64 `json:"cad"`
			Chf  float64 `json:"chf"`
			Clp  float64 `json:"clp"`
			Cny  float64 `json:"cny"`
			Czk  float64 `json:"czk"`
			Dkk  float64 `json:"dkk"`
			Dot  float64 `json:"dot"`
			Eos  float64 `json:"eos"`
			Eth  float64 `json:"eth"`
			Eur  float64 `json:"eur"`
			Gbp  float64 `json:"gbp"`
			Hkd  float64 `json:"hkd"`
			Huf  float64 `json:"huf"`
			Idr  float64 `json:"idr"`
			Ils  float64 `json:"ils"`
			Inr  float64 `json:"inr"`
			Jpy  float64 `json:"jpy"`
			Krw  float64 `json:"krw"`
			Kwd  float64 `json:"kwd"`
			Lkr  float64 `json:"lkr"`
			Ltc  float64 `json:"ltc"`
			Mmk  float64 `json:"mmk"`
			Mxn  float64 `json:"mxn"`
			Myr  float64 `json:"myr"`
			Ngn  float64 `json:"ngn"`
			Nok  float64 `json:"nok"`
			Nzd  float64 `json:"nzd"`
			Php  float64 `json:"php"`
			Pkr  float64 `json:"pkr"`
			Pln  float64 `json:"pln"`
			Rub  float64 `json:"rub"`
			Sar  float64 `json:"sar"`
			Sek  float64 `json:"sek"`
			Sgd  float64 `json:"sgd"`
			Thb  float64 `json:"thb"`
			Try  float64 `json:"try"`
			Twd  float64 `json:"twd"`
			Uah  float64 `json:"uah"`
			Usd  float64 `json:"usd"`
			Vef  float64 `json:"vef"`
			Vnd  float64 `json:"vnd"`
			Xag  float64 `json:"xag"`
			Xau  float64 `json:"xau"`
			Xdr  float64 `json:"xdr"`
			Xlm  float64 `json:"xlm"`
			Xrp  float64 `json:"xrp"`
			Yfi  float64 `json:"yfi"`
			Zar  float64 `json:"zar"`
			Bits float64 `json:"bits"`
			Link float64 `json:"link"`
			Sats float64 `json:"sats"`
		} `json:"market_cap_change_percentage_24h_in_currency"`
		TotalSupply       float64   `json:"total_supply"`
		MaxSupply         float64   `json:"max_supply"`
		CirculatingSupply float64   `json:"circulating_supply"`
		LastUpdated       time.Time `json:"last_updated"`
	} `json:"market_data"`
	CommunityData struct {
		FacebookLikes            interface{} `json:"facebook_likes"`
		TwitterFollowers         int         `json:"twitter_followers"`
		RedditAveragePosts48H    float64     `json:"reddit_average_posts_48h"`
		RedditAverageComments48H float64     `json:"reddit_average_comments_48h"`
		RedditSubscribers        int         `json:"reddit_subscribers"`
		RedditAccountsActive48H  int         `json:"reddit_accounts_active_48h"`
		TelegramChannelUserCount int         `json:"telegram_channel_user_count"`
	} `json:"community_data"`

	StatusUpdates []interface{} `json:"status_updates"`
	LastUpdated   time.Time     `json:"last_updated"`
	Tickers       []struct {
		Base   string `json:"base"`
		Target string `json:"target"`
		Market struct {
			Name                string `json:"name"`
			Identifier          string `json:"identifier"`
			HasTradingIncentive bool   `json:"has_trading_incentive"`
		} `json:"market"`
		Last          float64 `json:"last"`
		Volume        float64 `json:"volume"`
		ConvertedLast struct {
			Btc float64 `json:"btc"`
			Eth float64 `json:"eth"`
			Usd float64 `json:"usd"`
		} `json:"converted_last"`
		ConvertedVolume struct {
			Btc float64 `json:"btc"`
			Eth int     `json:"eth"`
			Usd int     `json:"usd"`
		} `json:"converted_volume"`
		TrustScore             string      `json:"trust_score"`
		BidAskSpreadPercentage float64     `json:"bid_ask_spread_percentage"`
		Timestamp              time.Time   `json:"timestamp"`
		LastTradedAt           time.Time   `json:"last_traded_at"`
		LastFetchAt            time.Time   `json:"last_fetch_at"`
		IsAnomaly              bool        `json:"is_anomaly"`
		IsStale                bool        `json:"is_stale"`
		TradeURL               string      `json:"trade_url"`
		TokenInfoURL           interface{} `json:"token_info_url"`
		CoinID                 string      `json:"coin_id"`
		TargetCoinID           string      `json:"target_coin_id,omitempty"`
	} `json:"tickers"`
}
